import {
  FiCalendar,
  FiAward,
  FiPackage,
  FiTruck,
  FiClock,
  FiShield,
  FiMessageCircle,
  FiX,
  FiCheck,
} from "react-icons/fi";
import { PlanDefinition } from "./types";

export const PLANS: PlanDefinition[] = [
  {
    id: "trial",
    name: "7-Day Trial Plan",
    badge: "ONE-TIME OFFER",
    quantity: "7 consecutive mornings of fresh farm milk delivery",
    price: 525,
    originalPrice: 595,
    savingsText: "Save ₹70",
    rateText: "₹75 / litre",
    periodLabel: "one-time offer",
    description: "7 consecutive mornings of farm-fresh pure A2 Gir cow milk delivered right to your doorstep.",
    icon: FiCalendar,
    gradient: "from-[#FAF6F0] via-white to-[#FFFDF7]",
    borderColor: "border-[#E8DFD4]",
    features: [
      { text: "7 consecutive morning deliveries", icon: FiTruck },
      { text: "Delivered fresh before 10 AM", icon: FiClock },
      { text: "Sealed reusable glass bottles", icon: FiShield },
      { text: "Daily morning WhatsApp updates", icon: FiMessageCircle },
      { text: "Zero commitment • Cancel anytime", icon: FiX },
    ],
    highlighted: false,
    ctaText: "Start 7-Day Trial",
    orderItem: {
      id: "item_trial_7d",
      name: "7-Day Starter Trial Plan (1L Daily Morning Delivery)",
      quantity: 7,
      price: 525,
      unit: "7 Litres",
    },
  },
  {
    id: "monthly",
    name: "Monthly Subscription",
    badge: "MOST POPULAR",
    quantity: "1L Daily (30L / mo)",
    price: 2250,
    originalPrice: null,
    savingsText: null,
    rateText: "₹75 / delivery",
    periodLabel: "/ month",
    description: "Our flagship family plan with automatic morning delivery, zero hassle, and total flexibility.",
    icon: FiAward,
    gradient: "from-[#FAF3EA] via-white to-[#FFFDF7]",
    borderColor: "border-[#5C1B13]",
    features: [
      { text: "1L delivered fresh daily before 10 AM", icon: FiTruck },
      { text: "Flexible pause / vacation mode", icon: FiCalendar },
      { text: "Sealed reusable glass bottles", icon: FiShield },
      { text: "WhatsApp updates & instant pause/skip", icon: FiMessageCircle },
      { text: "Priority morning delivery slot", icon: FiClock },
    ],
    highlighted: true,
    ctaText: "Subscribe Monthly",
    orderItem: {
      id: "item_monthly_30d",
      name: "Monthly Subscription Plan (1L Daily Morning Delivery)",
      quantity: 30,
      price: 2250,
      unit: "30 Litres",
    },
  },
  {
    id: "single",
    name: "Buy Once (1 Litre)",
    badge: "SAMPLE BOTTLE",
    quantity: "Order single bottles (0 of 7 used)",
    price: 85,
    originalPrice: null,
    savingsText: null,
    rateText: "₹85 / bottle",
    periodLabel: "one-time order",
    description: "Taste test our rich farm milk with a single bottle before starting a daily subscription.",
    icon: FiPackage,
    gradient: "from-slate-50 via-white to-[#FFFDF7]",
    borderColor: "border-[#E8DFD4]",
    features: [
      { text: "1 Litre pure farm A2 Gir cow milk", icon: FiCheck },
      { text: "Morning doorstep delivery before 10 AM", icon: FiClock },
      { text: "Sealed sanitized glass bottle", icon: FiShield },
      { text: "Instant WhatsApp confirmation", icon: FiMessageCircle },
      { text: "Single order • Zero commitment", icon: FiX },
    ],
    highlighted: false,
    ctaText: "Order Single Bottle",
    orderItem: {
      id: "item_single_1l",
      name: "1 Litre Pure A2 Gir Cow Milk (Chilled Glass Bottle)",
      quantity: 1,
      price: 85,
      unit: "1L Bottle",
    },
  },
];

export const INCLUDED_PERKS = [
  { icon: FiTruck, label: "Free 10 AM Delivery" },
  { icon: FiShield, label: "Zero Plastic Glass" },
  { icon: FiMessageCircle, label: "WhatsApp Pause/Skip" },
  { icon: FiCheck, label: "Money-Back Promise" },
] as const;

export const PLANS_BY_ID = Object.fromEntries(PLANS.map((p) => [p.id, p])) as Record<
  "trial" | "monthly" | "single",
  PlanDefinition
>;
